---

# Variables definition
# Pycharm, target and working directories: C:\Users\victorm\PycharmProjects\pythonProject1\auto
# set working dir below to be same as this
# Version label
latest_24hrs:
  enable: !!bool False     # if TRUE just retrieves + compares data from  midnight to midnight yesterday ONLY, if FALSE will take hard coded start time in py files

dirs:
  SR_to_json_output: !!str './output/SR/SR_daily.json'
  SR_to_csv_output: !!str './output/SR/testSR.csv'
  ED_daily_to_csv_output: !!str './output/EngDetailedReport/testED-Daily.csv'
  ED_column_headers: !!str './output/EngDetailedReport/testED-DailyNotReconciled.csv' # csv showing calls in Analytics ED but not in AWE S&R
  SR_column_headers: !!str './output/SR/testSR-DailyNotReconciled.csv' # csv showing calls in Analytics ED but not in AWE S&R
  #ED_interval_to_csv_output: !!str './output/EngDetailedReport/testED-Interval.csv'

urls:
  url: !!str "https://releasev2.cc.avayacloud.com"       # CCaaS url, prod release v2
  url_api_token: !!str "/auth/realms/IKHHJK/protocol/openid-connect/token"    # CCaaS token request url
  url_AnalyticsDailyDetailed: !!str "/api/analytics/historical/v1beta/accounts/IKHHJK/reports/EngagementDetail?interval=starting:" # CCaaS analytics ED API REQUEST URL
  url_AnalyticsDailyDetailed_pageSize: !!int 30 # ED request pageSize, equivalent to response number engagements per page
  url_wfo: !!str "wfo.a31.verintcloudservices.com"    # AWE system endpoint url
  url_wfo_captVerifapi: !!str "/api/av/capture_verification/v1/call_segments/issues/search/csv"   # AWE capt verif request url
  url_wfo_SearchReplayapi: !!str "/daswebapi/Query/ExecuteDynamicQuery"                           # AWE S&R request url
  url_wfo_token: !!str "https://wfo.a31.verintcloudservices.com/wfo/rest/core-api/auth/token"     # AWE token request url
# CCaaS API credentials
auth:
  clientid : !!str "wfm"                                          # Analytics clientid
  secret : !!str "nu6rSdYUVn0ooaXugpGmdkoXs2aEGdhd"               # Analytics secret
  wfo_token_user: !!str "api_user@verintnew01.prodreleasev2.com"  # Verint API user
  wfo_token_password: !!str "1_Abc_123"                           # Verint API password

logs:
  log_level : !!str "DEBUG" # all capital letters required for this field




# LOG LEVELS
# Level	Numeric Value	Description
# Critical	50	Highest severity messages; may cause a program to crash or exit.
# Error	40	High severity messages generally related to an operation failing that does not cause the program to crash or exit.
# Warning	30	Potentially negative events that may cause abnormal operation or otherwise require attention (such as the use of a deprecated API).
# Info	20	Messages that log standard/expected events.
# Debug	10	Messages useful for debugging how an application is running.
# Notset	0	Default level when a new logger is created. Setting the root logger to NOTSET logs all messages. For other loggers, NOTSET messages are delegated to parent loggers until a level other than NOTSET is found.

#T1 tests:
#1: SignOnWebpageTitle
#2: Usernnme_logon_filed_available
#3: WFO_Version_frontPage
#4: Tenant_admin_signin
#5: accessInteractionsSearchPage
#6: searchCallsLast7d
#7: searchCallFromToday 
#8: searchCallDateString ( defined config.yaml)
#9: searchCallUserString ( defined config.yaml)
#10: logout

#T0 tests:
#1: SignOnWebpageTitle
#2: Usernnme_logon_filed_available
#3: WFO_Version_frontPage
#4: Tenant_admin_signin